// Multi-language Support for Elder Joy Care Center
// Languages: English (en), Hindi (hi), Marathi (mr)

const translations = {
    en: {
        // Navigation
        "nav.home": "Home",
        "nav.about": "About Us",
        "nav.services": "Services",
        "nav.donation": "Donation",
        "nav.volunteer": "Volunteer",
        "nav.contact": "Contact",

        // Hero Section
        "hero.title": "Elderly Care NGO in Nagpur — Where Every Elder Lives with Dignity",
        "hero.subtitle": "This is not just an old age home. It is a home of dignity, safety, and belonging.",
        "hero.highlight": "Smile in Peace and Love.",
        "hero.donateBtn": "Donate Now",
        "hero.volunteerBtn": "Become a Volunteer",

        // Mission Section
        "mission.heading": "Because Growing Old Should Never Mean Being Alone",
        "mission.description": "At our Elderly Care NGO in Nagpur, we believe that every senior deserves respect, care, and a life filled with peace and dignity. We exist to ensure that elders—especially those who are vulnerable, abandoned, or physically challenged—are cared for with compassion, medical responsibility, and human warmth.",

        // Who We Are Section
        "home.careDecor": "Care",
        "home.whoWeAre": "Who We Are",
        "home.trustedTitle": "A Trusted Senior Citizen Care NGO in Maharashtra",
        "home.charitableText": "We are a charitable organization dedicated to elderly care and support for physically challenged individuals.",
        "home.missionIntro": "Our mission is simple yet powerful:",
        "home.missionStatement": "To serve elders as family — with empathy, integrity, and professional care.",
        "home.provideServicesTo": "We provide free and supported services to:",
        "home.serviceList1": "Senior citizens aged 75 years and above",
        "home.serviceList2": "Physically challenged individuals (no age limit)",
        "home.serviceList3": "Elders who lack financial or family support",
        "home.structuredCare": "Through structured care, medical attention, and emotional companionship, we help elders live their later years with comfort and confidence.",

        // Services Section
        "home.servicesTitle": "Our Elderly Care Services in Nagpur",
        "home.servicesSubtitle": "Comprehensive, Compassionate & Dignified Care",
        "home.servicesDesc": "We offer a wide range of senior citizen care services in Maharashtra, designed to meet physical, emotional, and medical needs.",
        "home.serviceCardTitle1": "Assisted Living Care",
        "home.serviceCardDesc1": "For elders who need daily medical supervision and personal assistance.",
        "home.serviceCardTitle2": "Independent Living",
        "home.serviceCardDesc2": "For seniors who are medically stable but seek community, safety, and support.",
        "home.serviceCardTitle3": "Home Healthcare Services",
        "home.serviceCardDesc3": "Professional nursing and caregiver support for elders who prefer care at home in Nagpur.",
        "home.serviceCardTitle4": "Dementia & Memory Care",
        "home.serviceCardDesc4": "Secure, structured, and emotionally sensitive care for seniors with dementia.",
        "home.serviceCardTitle5": "Post-Operative & Recovery Care",
        "home.serviceCardDesc5": "Support for elders recovering from surgery, injury, or hospitalization.",
        "home.serviceCardTitle6": "Chronic Illness Management",
        "home.serviceCardDesc6": "Care for arthritis, heart disease, asthma, cancer, and long-term conditions.",
        "home.exploreServicesBtn": "Explore All Services",

        // Trust Section
        "home.trustTitle": "Why Families Trust Us",
        "home.trustSubtitle": "A Caring Old Age Home in Nagpur with Proven Impact",
        "home.trustList1": "200+ Beds dedicated to elderly care",
        "home.trustList2": "Trained nurses, caregivers & medical staff",
        "home.trustList3": "Free care for seniors aged 75+",
        "home.trustList4": "Free support for physically challenged individuals",
        "home.trustList5": "24/7 supervision & medical monitoring",
        "home.trustList6": "Focus on emotional well-being, dignity & respect",

        // Support Section
        "home.supportTitle": "Your Support Changes Lives",
        "home.supportSubtitle": "Donate to Elderly Care in Nagpur",
        "home.supportDesc": "Many elders come to us with no income, no family support, and serious health needs. Your contribution helps us provide:",
        "home.supportList1": "Free medical treatment & nursing care",
        "home.supportList2": "Nutritious meals & safe shelter",
        "home.supportList3": "Medicines, diagnostics & wellness activities",
        "home.supportList4": "Emotional support and companionship",
        "home.transparencyNote": "Transparent usage | Donation receipts available | CSR-friendly",
        "home.donateNowBtn": "Donate Now – Support an Elder Today",

        // CTA Section
        "home.ctaTitle": "Together, We Can Care Better",
        "home.ctaDesc": "A society is truly progressive when it respects and protects its elders. With your support, we can ensure that no elder in Nagpur is left behind.",
        "home.makeDonationBtn": "Make a Donation",
        "home.contactTeamBtn": "Contact Our Team",

        // Volunteer Page
        "volunteer.heroTitle": "Volunteer With Us —",
        "volunteer.heroSpan": "Be the Reason an Elder Smiles",
        "volunteer.subtitle": "Volunteer for an Elderly Care NGO in Nagpur",
        "volunteer.intro1": "At Elder Joy Care Center, volunteers are the heart of our mission. Your time, skills, and kindness directly impact the lives of elderly individuals who need care, companionship, and dignity.",
        "volunteer.intro2": "Whether you're a student, working professional, retiree, or anyone who wants to give back—you can make a tangible difference.",
        "volunteer.alreadyVolunteer": "Already a Volunteer?",
        "volunteer.generateId": "If you've completed your registration with us, you can generate your official volunteer ID card below.",
        "volunteer.generateIdBtn": "Generate ID Card Now",

        // Footer
        "footer.quickLinks": "Quick Links",
        "footer.contact": "Contact Us",
        "footer.follow": "Follow Us",
        "footer.copyright": "Copyright © 2026 Elder Joy Care Center | Powered by",

        // About Page
        "about.introTitle": "A Charitable Trust Dedicated to Elderly & Physically Challenged Care",
        "about.introText": "We are a charitable trust focused on elderly care and support for physically challenged individuals in Nagpur.",
        "about.belief": "\"Every human life deserves dignity, care, and respect—at every stage and in every ability.\"",
        "about.whoWeServeTitle": "Who We Serve",
        "about.seniorCitizens": "Senior Citizens",
        "about.seniorCitizensDesc": "Especially those aged 75 years and above who need dedicated support.",
        "about.physicallyChallenged": "Physically Challenged",
        "about.physicallyChallengedDesc": "Universal assistance for individuals of all ages with varied abilities.",
        "about.vulnerableElders": "Vulnerable Elders",
        "about.vulnerableEldersDesc": "Supporting those who lack family support or financial stability.",
        "about.missionTitle": "Our Mission",
        "about.missionDesc": "\"Elder Joy Care Center is committed to providing a nurturing home where residents experience warmth, care, and a sense of belonging.\"",
        "about.visionTitle": "Our Vision",
        "about.visionDesc": "\"We aim to be a warm and caring home, treating everyone like family, creating an environment where residents thrive.\"",
        "about.valuesTitle": "Our Values",
        "about.dignityTitle": "Dignity Above All",
        "about.dignityDesc": "We respect every individual’s life journey and ensure that care is delivered with dignity.",
        "about.compassionTitle": "Compassion in Action",
        "about.compassionDesc": "Care is not only medical—it is emotional, social, and human.",
        "about.integrityTitle": "Integrity & Transparency",
        "about.integrityDesc": "We are committed to ethical operations and responsible use of resources.",
        "about.communityTitle": "Community Responsibility",
        "about.visionDesc": "To create a society where every elder feels valued, supported, and empowered to live with dignity and joy.",
        "about.approachTitle": "The Heart of Our Approach",
        "about.approachDesc": "Our approach combines structured healthcare systems with deep emotional understanding, allowing elders to live with comfort rather than fear, and confidence rather than dependency.",

        // Services Page
        "services.heroTitle": "Comprehensive Elderly Care Services in Nagpur",
        "services.heroDesc": "Our Elderly Care NGO provides holistic support through medical care, daily assistance, and emotional well-being.",
        "services.eligibilityTitle": "Who Can Avail Our Elderly Care Services",
        "services.eligibilitySubtitle": "Eligibility & Support Structure",
        "services.eligibilityQuote": "\"Our services are provided based on need, vulnerability, and dignity.\"",
        "services.senior75": "Senior Citizens 75+",
        "services.freeCare": "Free Elderly Care Services",
        "services.physicallyChallenged": "Physically Challenged",
        "services.freeSupport": "Free Care & Support",
        "services.seniorsBelow75": "Seniors below 75",
        "services.supportedPlans": "Supported Plans",
        "services.nursingTitle": "Elderly Nursing Care in Nagpur",
        "services.nursingDesc": "We provide professional, round-the-clock elderly nursing care delivered by trained staff.",
        "services.medicalTitle": "Medical Support & Regular Health Check-Ups",
        "services.medicalDesc": "Our structured medical care model focuses on early detection and continuity.",
        "services.fitnessTitle": "Yoga & Light Physical Fitness Programs",
        "services.fitnessDesc": "Physical movement plays a vital role in maintaining independence.",
        "services.homeVisitTitle": "Home Visits & Elderly Care at Home",
        "services.homeVisitDesc": "For seniors who prefer to age in their own homes, we offer professional home care.",
        "services.nursingSubtitle": "Nursing support includes:",
        "services.nursingList1": "Assistance with daily activities such as bathing, feeding, and mobility",
        "services.nursingList2": "Medication administration and monitoring",
        "services.nursingList3": "Post-hospitalization nursing care",
        "services.nursingList4": "Support for bedridden and mobility-impaired elders",
        "services.nursingList5": "Compassionate end-of-life care",
        "services.nursingNote": "All care is delivered patiently and respectfully, prioritizing dignity over routine.",
        "services.medicalSubtitle": "Medical services include:",
        "services.medicalList1": "Regular doctor consultations",
        "services.medicalList2": "Monitoring of vital parameters (BP, sugar, O2)",
        "services.medicalList3": "Preventive health check-ups",
        "services.medicalList4": "Management of chronic conditions",
        "services.medicalList5": "Coordination with hospitals and specialists",
        "services.medicalNote": "This ensures consistent medical oversight and timely intervention.",
        "services.fitnessItem1Title": "Movement",
        "services.fitnessItem1Desc": "Chair yoga and guided stretching",
        "services.fitnessItem2Title": "Breathing",
        "services.fitnessItem2Desc": "Exercises for optimized lung health",
        "services.fitnessItem3Title": "Flexibility",
        "services.fitnessItem3Desc": "Balance and flexibility routines",
        "services.fitnessItem4Title": "Relaxation",
        "services.fitnessItem4Desc": "Stress-reduction sessions",
        "services.fitnessNote": "These programs help improve mobility, reduce discomfort, and enhance confidence among elders and physically challenged individuals.",
        "services.homeVisitSubtitle": "Home-based support includes:",
        "services.homeVisitList1": "Nursing and caregiver visits",
        "services.homeVisitList2": "Health check-ups conducted at home",
        "services.homeVisitList3": "Medication reminders and assistance",
        "services.homeVisitList4": "Emotional support and regular monitoring",
        "services.homeVisitList5": "Guidance for family members and caregivers",
        "services.homeVisitNote": "This service allows elders to remain safe and supported within familiar surroundings.",
        "services.comparisonTitle": "Free vs Supported Elderly Care Services",
        "services.comparisonSubtitle": "Transparent & Ethical Structure",
        "services.comparisonFreeTitle": "Free Care Services",
        "services.comparisonFreeList1": "Senior citizens aged 75 years and above",
        "services.comparisonFreeList2": "Physically challenged individuals (any age)",
        "services.comparisonFreeList3": "Includes nursing, medical, wellness & daily assistance",
        "services.comparisonPaidTitle": "Supported Services",
        "services.comparisonPaidList1": "Senior citizens below 75 years",
        "services.comparisonPaidList2": "Specialized or extended medical care",
        "services.comparisonPaidList3": "Customized elderly care plans",
        "services.comparisonNote": "All service structures are communicated clearly, ethically, and without hidden conditions.",

        // Donation Page
        "donation.heroTitle": "Donate for Elderly Care in Nagpur",
        "donation.heroSubtitle": "Give Dignity, Comfort & Hope",
        "donation.heroDesc": "Your kindness helps ensure that growing old never means being forgotten.",
        "donation.formTitle": "Donate Now & Make a Difference",
        "donation.formIntro": "Your support provides food, medicine, and dignity to our elders.",
        "donation.amountLabel": "Select Amount (INR)",
        "donation.minAmount": "Minimum donation: ₹100",
        "donation.personalDetails": "Personal Details",
        "donation.fullName": "Full Name",
        "donation.email": "Email Address",
        "donation.phone": "Phone Number",
        "donation.btn": "Donate Now",
        "donation.secured": "Secured Payment",
        "donation.whyMattersTitle": "Why Your Donation Matters",
        "donation.whyMattersDesc": "Across communities, many elders face challenges that make daily life difficult.",
        "donation.impact1": "Loneliness and abandonment",
        "donation.impact2": "Chronic health conditions",
        "donation.impact3": "Limited or no income",
        "donation.impact4": "Physical challenges",
        "donation.usageTitle": "How Your Donation Is Used",
        "donation.usageDesc": "We believe every donor deserves clarity and confidence.",
        "donation.medical": "Medical Care & Nursing",
        "donation.food": "Food & Essentials",
        "donation.shelter": "Safe Shelter",
        "donation.wellness": "Emotional Wellness",
        "donation.impactNote": "Without timely support, their later years become a struggle instead of a time of peace. When you donate to an elderly care NGO in Nagpur, you help ensure that no elder is left without care, safety, or dignity.",
        "donation.impactQuote": "\"Your generosity restores not just health—but hope and self-worth.\"",
        "donation.usageIntro": "We believe every donor deserves clarity and confidence. Each contribution is directed toward real, measurable care.",
        "donation.medicalList1": "Regular doctor consultations",
        "donation.medicalList2": "Medicines and ongoing treatment",
        "donation.medicalList3": "Nursing support for hygiene & mobility",
        "donation.foodList1": "Fresh, balanced meals",
        "donation.foodList2": "Clean drinking water",
        "donation.foodList3": "Personal hygiene items",
        "donation.shelterList1": "Secure accommodation",
        "donation.shelterList2": "Clean, elder-friendly spaces",
        "donation.shelterList3": "24/7 supervision and assistance",
        "donation.wellnessList1": "Yoga and light fitness",
        "donation.wellnessList2": "Emotional companionship",
        "donation.wellnessList3": "Social joyful activities",
        "donation.helpsTitle": "Who Your Donation Helps",
        "donation.helps1Title": "Senior citizens aged 75+",
        "donation.helps1Sub": "(Free care provided)",
        "donation.helps2Title": "Physically Challenged",
        "donation.helps2Sub": "(Universal support)",
        "donation.helps3Title": "Elders without Family",
        "donation.helps3Sub": "(Compassionate aid)",
        "donation.helpsNote": "Your generosity ensures care is provided based on need, not affordability.",
        "donation.trustTitle": "Safe Online Donation & Receipt Assurance",
        "donation.trustIntro": "We offer secure and transparent donation options:",
        "donation.trustList1": "Safe and encrypted payment gateways",
        "donation.trustList2": "Instant acknowledgment",
        "donation.trustList3": "Donation receipt provided",
        "donation.trustList4": "Transparent accounting and ethical governance",
        "donation.commitmentTitle": "Our Commitment to Trust",
        "donation.commitmentList1": "• Ethical use of funds",
        "donation.commitmentList2": "• Clear documentation",
        "donation.commitmentList3": "• Honest communication",
        "donation.commitmentList4": "• Long-term impact focus",
        "donation.commitmentNote": "Every rupee is treated as a responsibility.",

        // Contact Page
        "contact.heroTitle": "Get in Touch With Us",
        "contact.heroDesc": "We would love to hear from you. Whether you have questions or need assistance.",
        "contact.locationTitle": "Our Location",
        "contact.phoneTitle": "Phone",
        "contact.emailTitle": "Email",
        "contact.whoTitle": "Who Should Contact Us?",
        "contact.families": "Families & Caregivers",
        "contact.familiesDesc": "Reaching out for care is an emotional decision. We will guide you patiently.",
        "contact.donors": "Donors & Partners",
        "contact.donorsDesc": "Together, we can create lasting impact.",
        "contact.volunteers": "Volunteers",
        "contact.volunteersDesc": "Your time and compassion can change lives.",
        "contact.volunteerBtn": "Become a Volunteer",
        "contact.supportBtn": "Support Our Elders",
        "contact.address": "89, near NIT Garden, Telecom Nagar, Pratap Nagar, Nagpur, Maharashtra 440022",
        "contact.partnersList1": "Donate to support elderly care",
        "contact.partnersList2": "Explore long-term or CSR partnerships",
        "contact.partnersList3": "Understand how your contribution creates impact",
        "contact.partnersNote": "We believe in complete transparency and accountability in all our operations.",

        // Volunteer Page (Additional)
        "volunteer.whyMatters": "Why Volunteering Matters",
        "volunteer.whyMattersDesc": "As people age, what they miss most is often not medicine—but companionship.",
        "volunteer.role1": "Spend Time With Elders",
        "volunteer.role2": "Wellness & Activity Support",
        "volunteer.role3": "Care & Support Assistance",
        "volunteer.role4": "Administrative & Outreach",
        "volunteer.role5": "CSR & Group Volunteering",
        "volunteer.gainTitle": "What You Gain as a Volunteer",
        "volunteer.whoCanTitle": "Who Can Volunteer?",
        "volunteer.rolesTitle": "Volunteer Roles & Opportunities",
        "volunteer.readyTitle": "Ready to Make a Difference?",
        "volunteer.readyDesc": "Join our community of compassionate volunteers and bring joy to the lives of our elders.",
        "volunteer.registerCTA": "Register as a Volunteer",
        "volunteer.joinCTA": "Join Our Community of Care",
        "volunteer.formIntro": "Fill in your details to become part of our volunteer community",
        "volunteer.registerTitle": "Volunteer Registration",
        "volunteer.formName": "Full Name",
        "volunteer.formEmail": "Email Address",
        "volunteer.formPhone": "Phone Number",
        "volunteer.formDOB": "Date of Birth",
        "volunteer.formQual": "Qualification / Designation",
        "volunteer.formArea": "Area of Interest",
        "volunteer.formAvail": "Availability",
        "volunteer.submitBtn": "Submit Registration",
        "volunteer.benefit1": "Reduce loneliness and emotional isolation",
        "volunteer.benefit2": "Support physically challenged individuals",
        "volunteer.benefit3": "Strengthen community responsibility",
        "volunteer.benefit4": "Create joyful moments through your presence",
        "volunteer.highlightText": "Volunteering reminds our elders that they are seen, valued, and respected.",
        "volunteer.whoCard1": "Students looking for meaningful social work experience",
        "volunteer.whoCard2": "Working professionals who want to give back to society",
        "volunteer.whoCard3": "Retirees who wish to share their wisdom and time",
        "volunteer.whoCard4": "Corporate groups interested in CSR activities",
        "volunteer.whoCard5": "Artists, musicians, or storytellers who can bring joy",
        "volunteer.whoCard6": "Anyone with empathy, patience, and a kind heart",
        "volunteer.gain1": "A sense of purpose and fulfillment",
        "volunteer.gain2": "Real-world experience in social work and caregiving",
        "volunteer.gain3": "Meaningful connections with elders and fellow volunteers",
        "volunteer.gain4": "Personal growth through empathy and patience",
        "volunteer.gain5": "Volunteer certificate and recognition",
        "volunteer.gain6": "Opportunity to make a tangible difference in someone's life",
        "volunteer.role1Item1": "Engage in conversations and companionship",
        "volunteer.role1Item2": "Listen to their life stories and experiences",
        "volunteer.role1Item3": "Share meals and celebrate special occasions",
        "volunteer.role1Item4": "Play indoor games or read to them",
        "volunteer.role2Item1": "Organize gentle physical activities or yoga sessions",
        "volunteer.role2Item2": "Lead music, art, or craft workshops",
        "volunteer.role2Item3": "Assist in recreational outings and group activities",
        "volunteer.role2Item4": "Help with gardening or light outdoor activities",
        "volunteer.role3Item1": "Help with daily mobility and movement support",
        "volunteer.role3Item2": "Assist during meal times",
        "volunteer.role3Item3": "Support hygiene and personal care routines (with training)",
        "volunteer.role3Item4": "Accompany elders to medical appointments",
        "volunteer.role4Item1": "Help with documentation and record-keeping",
        "volunteer.role4Item2": "Assist in social media and awareness campaigns",
        "volunteer.role4Item3": "Support fundraising and donation drives",
        "volunteer.role4Item4": "Coordinate volunteer schedules and events",
        "volunteer.role5Item1": "Organize team-building activities with elders",
        "volunteer.role5Item2": "Conduct health camps or awareness sessions",
        "volunteer.role5Item3": "Sponsor special events (birthdays, festivals)",
        "volunteer.role5Item4": "Provide skill-based volunteering (legal, medical, tech support)"
    },

    hi: {
        // Navigation (Hindi)
        "nav.home": "होम",
        "nav.about": "हमारे बारे में",
        "nav.services": "सेवाएं",
        "nav.donation": "दान",
        "nav.volunteer": "स्वयंसेवक",
        "nav.contact": "संपर्क",

        // Hero Section (Hindi)
        "hero.title": "नागपुर में बुजुर्ग देखभाल एनजीओ — जहां हर बुजुर्ग सम्मान के साथ जीता है",
        "hero.subtitle": "यह सिर्फ एक वृद्धाश्रम नहीं है। यह सम्मान, सुरक्षा और अपनेपन का घर है।",
        "hero.highlight": "शांति और प्यार में मुस्कुराएं।",
        "hero.donateBtn": "अभी दान करें",
        "hero.volunteerBtn": "स्वयंसेवक बनें",

        // Mission Section (Hindi)
        "mission.heading": "क्योंकि बूढ़ा होने का मतलब कभी अकेला होना नहीं होना चाहिए",
        "mission.description": "नागपुर में हमारे बुजुर्ग देखभाल एनजीओ में, हम मानते हैं कि हर बुजुर्ग सम्मान, देखभाल और शांति और गरिमा से भरा जीवन का हकदार है। हम यह सुनिश्चित करने के लिए मौजूद हैं कि बुजुर्गों की - विशेष रूप से जो कमजोर, परित्यक्त या शारीरिक रूप से विकलांग हैं - दयालुता, चिकित्सा जिम्मेदारी और मानवीय गर्मजोशी के साथ देखभाल की जाए।",

        // Who We Are Section (Hindi)
        "home.careDecor": "देखभाल",
        "home.whoWeAre": "हम कौन हैं",
        "home.trustedTitle": "महाराष्ट्र में एक विश्वसनीय वरिष्ठ नागरिक देखभाल एनजीओ",
        "home.charitableText": "हम बुजुर्गों की देखभाल और शारीरिक रूप से विकलांग व्यक्तियों के सहयोग के लिए समर्पित एक धर्मार्थ संगठन हैं।",
        "home.missionIntro": "हमारा मिशन सरल लेकिन शक्तिशाली है:",
        "home.missionStatement": "बुजुर्गों की परिवार की तरह सेवा करना — सहानुभूति, अखंडता और पेशेवर देखभाल के साथ।",
        "home.provideServicesTo": "हम निम्नलिखित को मुफ्त और समर्थित सेवाएं प्रदान करते हैं:",
        "home.serviceList1": "75 वर्ष और उससे अधिक आयु के वरिष्ठ नागरिक",
        "home.serviceList2": "शारीरिक रूप से विकलांग व्यक्ति (कोई आयु सीमा नहीं)",
        "home.serviceList3": "बुजुर्ग जिनके पास वित्तीय या पारिवारिक समर्थन नहीं है",
        "home.structuredCare": "संरचित देखभाल, चिकित्सा ध्यान और भावनात्मक साहचर्य के माध्यम से, हम बुजुर्गों को उनके बाद के वर्षों को आराम और आत्मविश्वास के साथ जीने में मदद करते हैं।",

        // Services Section (Hindi)
        "home.servicesTitle": "नागपुर में हमारी बुजुर्ग देखभाल सेवाएं",
        "home.servicesSubtitle": "व्यापक, दयालु और प्रतिष्ठित देखभाल",
        "home.servicesDesc": "हम महाराष्ट्र में वरिष्ठ नागरिक देखभाल सेवाओं की एक विस्तृत श्रृंखला प्रदान करते हैं, जो शारीरिक, भावनात्मक और चिकित्सा आवश्यकताओं को पूरा करने के लिए डिज़ाइन की गई हैं।",
        "home.serviceCardTitle1": "असिस्टेड लिविंग केयर",
        "home.serviceCardDesc1": "उन बुजुर्गों के लिए जिन्हें दैनिक चिकित्सा पर्यवेक्षण और व्यक्तिगत सहायता की आवश्यकता है।",
        "home.serviceCardTitle2": "इंडिपेंडेंट लिविंग",
        "home.serviceCardDesc2": "उन वरिष्ठ नागरिकों के लिए जो चिकित्सकीय रूप से स्थिर हैं लेकिन समुदाय, सुरक्षा और सहायता चाहते हैं।",
        "home.serviceCardTitle3": "घरेलू स्वास्थ्य सेवाएं",
        "home.serviceCardDesc3": "उन बुजुर्गों के लिए पेशेवर नर्सिंग और देखभालकर्ता सहायता जो नागपुर में घर पर देखभाल पसंद करते हैं।",
        "home.serviceCardTitle4": "डिमेंशिया और मेमोरी केयर",
        "home.serviceCardDesc4": "डिमेंशिया से पीड़ित वरिष्ठ नागरिकों के लिए सुरक्षित, संरचित और भावनात्मक रूप से संवेदनशील देखभाल।",
        "home.serviceCardTitle5": "पोस्ट-ऑपरेटिव्ह और रिकवरी केयर",
        "home.serviceCardDesc5": "सर्जरी, चोट या अस्पताल में भर्ती होने के बाद ठीक होने वाले बुजुर्गों के लिए सहायता।",
        "home.serviceCardTitle6": "पुरानी बीमारी का प्रबंधन",
        "home.serviceCardDesc6": "गठिया, हृदय रोग, अस्थमा, कैंसर और दीर्घकालिक स्थितियों के लिए देखभाल।",
        "home.exploreServicesBtn": "सभी सेवाएं देखें",

        // Trust Section (Hindi)
        "home.trustTitle": "परिवार हम पर क्यों भरोसा करते हैं",
        "home.trustSubtitle": "नागपुर में एक देखभाल करने वाला वृद्धाश्रम जिसका प्रभाव सिद्ध है",
        "home.trustList1": "बुजुर्गों की देखभाल के लिए समर्पित 200+ बिस्तर",
        "home.trustList2": "प्रशिक्षित नर्स, देखभालकर्ता और चिकित्सा कर्मचारी",
        "home.trustList3": "75+ आयु वर्ग के वरिष्ठ नागरिकों के लिए मुफ्त देखभाल",
        "home.trustList4": "शारीरिक रूप से विकलांग व्यक्तियों के लिए मुफ्त सहायता",
        "home.trustList5": "24/7 पर्यवेक्षण और चिकित्सा निगरानी",
        "home.trustList6": "भावनात्मक भलाई, गरिमा और सम्मान पर ध्यान",

        // Support Section (Hindi)
        "home.supportTitle": "आपका सहयोग जीवन बदल देता है",
        "home.supportSubtitle": "नागपुर में बुजुर्ग देखभाल के लिए दान करें",
        "home.supportDesc": "कई बुजुर्ग बिना आय, बिना पारिवारिक समर्थन और गंभीर स्वास्थ्य आवश्यकताओं के साथ हमारे पास आते हैं। आपका योगदान हमें प्रदान करने में मदद करता है:",
        "home.supportList1": "मुफ्त चिकित्सा उपचार और नर्सिंग देखभाल",
        "home.supportList2": "पौष्टिक भोजन और सुरक्षित आश्रय",
        "home.supportList3": "दवाएं, निदान और कल्याण गतिविधियां",
        "home.supportList4": "भावनात्मक समर्थन और साहचर्य",
        "home.transparencyNote": "पारदर्शी उपयोग | दान रसीदें उपलब्ध | सीएसआर-फ्रेंडली",
        "home.donateNowBtn": "अभी दान करें - आज ही एक बुजुर्ग का समर्थन करें",

        // CTA Section (Hindi)
        "home.ctaTitle": "साथ मिलकर, हम बेहतर देखभाल कर सकते हैं",
        "home.ctaDesc": "एक समाज वास्तव में प्रगतिशील होता है जब वह अपने बुजुर्गों का सम्मान और सुरक्षा करता है। आपके सहयोग से, हम यह सुनिश्चित कर सकते हैं कि नागपुर में कोई भी बुजुर्ग पीछे न छूटे।",
        "home.makeDonationBtn": "दान करें",
        "home.contactTeamBtn": "हमारी टीम से संपर्क करें",

        // Volunteer Page (Hindi)
        "volunteer.heroTitle": "हमारे साथ स्वयंसेवक बनें —",
        "volunteer.heroSpan": "एक बुजुर्ग की मुस्कान का कारण बनें",
        "volunteer.subtitle": "नागपुर में बुजुर्ग देखभाल एनजीओ के लिए स्वयंसेवक",
        "volunteer.intro1": "एल्डर जॉय केयर सेंटर में, स्वयंसेवक हमारे मिशन का दिल हैं। आपका समय, कौशल और दयालुता सीधे उन बुजुर्गों के जीवन को प्रभावित करती है जिन्हें देखभाल, साहचर्य और सम्मान की आवश्यकता है।",
        "volunteer.intro2": "चाहे आप छात्र हों, कामकाजी पेशेवर, सेवानिवृत्त, या कोई भी जो वापस देना चाहता है - आप एक वास्तविक अंतर कर सकते हैं।",
        "volunteer.alreadyVolunteer": "पहले से स्वयंसेवक हैं?",
        "volunteer.generateId": "यदि आपने हमारे साथ अपना पंजीकरण पूरा कर लिया है, तो आप नीचे अपना आधिकारिक स्वयंसेवक आईडी कार्ड बना सकते हैं।",
        "volunteer.generateIdBtn": "अभी आईडी कार्ड बनाएं",

        // Footer (Hindi)
        "footer.quickLinks": "त्वरित लिंक",
        "footer.contact": "संपर्क करें",
        "footer.follow": "हमें फॉलो करें",
        "footer.copyright": "कॉपीराइट © 2026 एल्डर जॉय केयर सेंटर | द्वारा संचालित",

        // About Page (Hindi)
        "about.introTitle": "बुजुर्गों और शारीरिक रूप से अक्षम लोगों की देखभाल के लिए समर्पित एक धर्मार्थ ट्रस्ट",
        "about.introText": "हम नागपुर में बुजुर्गों की देखभाल और शारीरिक रूप से विकलांग व्यक्तियों के सहयोग के लिए केंद्रित एक धर्मार्थ ट्रस्ट हैं।",
        "about.belief": "\"हर मानव जीवन सम्मान, देखभाल और आदर का हकदार है—हर चरण और हर क्षमता में।\"",
        "about.whoWeServeTitle": "हम किसकी सेवा करते हैं",
        "about.seniorCitizens": "वरिष्ठ नागरिक",
        "about.seniorCitizensDesc": "विशेष रूप से 75 वर्ष और उससे अधिक आयु के लोग जिन्हें समर्पित सहायता की आवश्यकता है।",
        "about.physicallyChallenged": "शारीरिक रूप से विकलांग",
        "about.physicallyChallengedDesc": "विभिन्न क्षमताओं वाले सभी आयु वर्ग के व्यक्तियों के लिए सार्वभौमिक सहायता।",
        "about.vulnerableElders": "कमजोर बुजुर्ग",
        "about.vulnerableEldersDesc": "उन लोगों का समर्थन करना जिनके पास पारिवारिक समर्थन या वित्तीय स्थिरता की कमी है।",
        "about.missionTitle": "हमारा मिशन",
        "about.missionDesc": "\"एल्डर जॉय केयर सेंटर एक पोषण घर प्रदान करने के लिए प्रतिबद्ध है जहां निवासी गर्मजोशी, देखभाल और अपनेपन का अनुभव करते हैं।\"",
        "about.visionTitle": "हमारा विजन (Vision)",
        "about.visionDesc": "एक ऐसा समाज बनाना जहां प्रत्येक वरिष्ठ नागरिक मूल्यवान, समर्थित और गौरव और खुशी के साथ जीने के लिए सशक्त महसूस करे।",
        "about.valuesTitle": "हमारे मूल्य",
        "about.dignityTitle": "गरिमा सर्वोपरि",
        "about.dignityDesc": "हम प्रत्येक व्यक्ति की जीवन यात्रा का सम्मान करते हैं और सुनिश्चित करते हैं कि देखभाल गरिमा के साथ दी जाए।",
        "about.compassionTitle": "कार्य में करुणा",
        "about.compassionDesc": "देखभाल केवल चिकित्सा नहीं है—यह भावनात्मक, सामाजिक और मानवीय है।",
        "about.integrityTitle": "अखंडता और पारदर्शिता",
        "about.integrityDesc": "हम नैतिक संचालन और संसाधनों के जिम्मेदार उपयोग के लिए प्रतिबद्ध हैं।",
        "about.communityTitle": "सामुदायिक जिम्मेदारी",
        "about.visionDesc": "एक ऐसा समाज बनाना जहां प्रत्येक वरिष्ठ नागरिक मूल्यवान, समर्थित और गौरव और खुशी के साथ जीने के लिए सशक्त महसूस करे।",
        "about.approachTitle": "हमारे दृष्टिकोण का हृदय",
        "about.approachDesc": "हमारा दृष्टिकोण संरचित स्वास्थ्य सेवा प्रणालियों को गहरी भावनात्मक समझ के साथ जोड़ता है, जिससे वरिष्ठ नागरिक भय के बजाय आराम और निर्भरता के बजाय आत्मविश्वास के साथ जी सकें।",

        // Services Page (Hindi)
        "services.heroTitle": "नागपुर में व्यापक बुजुर्ग देखभाल सेवाएं",
        "services.heroDesc": "हमारा एनजीओ चिकित्सा देखभाल, दैनिक सहायता और भावनात्मक भलाई के माध्यम से समग्र समर्थन प्रदान करता है।",
        "services.eligibilityTitle": "हमारी सेवाएं कौन प्राप्त कर सकता है",
        "services.eligibilitySubtitle": "पात्रता और सहायता संरचना",
        "services.eligibilityQuote": "\"हमारी सेवाएं आवश्यकता, भेद्यता और गरिमा के आधार पर प्रदान की जाती हैं।\"",
        "services.senior75": "वरिष्ठ नागरिक 75+",
        "services.freeCare": "मुफ्त बुजुर्ग देखभाल सेवाएं",
        "services.physicallyChallenged": "शारीरिक रूप से विकलांग",
        "services.freeSupport": "मुफ्त देखभाल और सहायता",
        "services.seniorsBelow75": "75 से कम उम्र के वरिष्ठ",
        "services.supportedPlans": "समर्थित योजनाएं",
        "services.nursingTitle": "नागपुर में नर्सिंग देखभाल",
        "services.nursingDesc": "हम प्रशिक्षित कर्मचारियों द्वारा चौबीसों घंटे पेशेवर नर्सिंग देखभाल प्रदान करते हैं।",
        "services.medicalTitle": "चिकित्सा सहायता और नियमित जांच",
        "services.medicalDesc": "हमारा चिकित्सा देखभाल मॉडल शुरुआती पहचान और निरंतरता पर केंद्रित है।",
        "services.fitnessTitle": "योग और हल्की फिटनेस",
        "services.fitnessDesc": "स्वतंत्रता बनाए रखने में शारीरिक गतिविधि महत्वपूर्ण भूमिका निभाती है।",
        "services.homeVisitTitle": "घर पर बुजुर्गों की देखभाल",
        "services.homeVisitDesc": "जो वरिष्ठ अपने घरों में रहना पसंद करते हैं, हम उनके लिए पेशेवर घरेलू देखभाल प्रदान करते हैं।",
        "services.nursingSubtitle": "नर्सिंग सहायता में शामिल हैं:",
        "services.nursingList1": "दैनिक गतिविधियों जैसे स्नान, भोजन और गतिशीलता में सहायता",
        "services.nursingList2": "दवा प्रशासन और निगरानी",
        "services.nursingList3": "अस्पताल में भर्ती होने के बाद नर्सिंग देखभाल",
        "services.nursingList4": "बिस्तर पर पड़े और चलने-फिरने में असमर्थ बुजुर्गों के लिए सहायता",
        "services.nursingList5": "करुणापूर्ण अंतिम समय की देखभाल",
        "services.nursingNote": "सभी देखभाल धैर्य और सम्मानपूर्वक दी जाती है, जिसमें दिनचर्या से अधिक गरिमा को प्राथमिकता दी जाती है।",
        "services.medicalSubtitle": "चिकित्सा सेवाओं में शामिल हैं:",
        "services.medicalList1": "नियमित डॉक्टर परामर्श",
        "services.medicalList2": "महत्वपूर्ण मापदंडों (बीपी, शुगर, ओ2) की निगरानी",
        "services.medicalList3": "निवारक स्वास्थ्य जांच",
        "services.medicalList4": "पुरानी स्थितियों का प्रबंधन",
        "services.medicalList5": "अस्पतालों और विशेषज्ञों के साथ समन्वय",
        "services.medicalNote": "यह निरंतर चिकित्सा निरीक्षण और समय पर हस्तक्षेप सुनिश्चित करता है।",
        "services.fitnessItem1Title": "आंदोलन",
        "services.fitnessItem1Desc": "कुर्सी योग और निर्देशित स्ट्रेचिंग",
        "services.fitnessItem2Title": "श्वास",
        "services.fitnessItem2Desc": "फेफड़ों के स्वास्थ्य के लिए व्यायाम",
        "services.fitnessItem3Title": "लचीलापन",
        "services.fitnessItem3Desc": "संतुलन और लचीलापन दिनचर्या",
        "services.fitnessItem4Title": "विश्राम",
        "services.fitnessItem4Desc": "तनाव कम करने के सत्र",
        "services.fitnessNote": "ये कार्यक्रम बुजुर्गों और शारीरिक रूप से विकलांग व्यक्तियों के बीच गतिशीलता में सुधार, असुविधा कम करने और आत्मविश्वास बढ़ाने में मदद करते हैं।",
        "services.homeVisitSubtitle": "घर-आधारित सहायता में शामिल हैं:",
        "services.homeVisitList1": "नर्सिंग और देखभालकर्ता के दौरे",
        "services.homeVisitList2": "घर पर की जाने वाली स्वास्थ्य जांच",
        "services.homeVisitList3": "दवा की याद दिलाना और सहायता",
        "services.homeVisitList4": "भावनात्मक समर्थन और नियमित निगरानी",
        "services.homeVisitList5": "परिवार के सदस्यों और देखभाल करने वालों के लिए मार्गदर्शन",
        "services.homeVisitNote": "यह सेवा बुजुर्गों को परिचित परिवेश में सुरक्षित और समर्थित रहने की अनुमति देती है।",
        "services.comparisonTitle": "मुफ्त बनाम समर्थित बुजुर्ग देखभाल सेवाएं",
        "services.comparisonSubtitle": "पारदर्शी और नैतिक संरचना",
        "services.comparisonFreeTitle": "मुफ्त देखभाल सेवाएं",
        "services.comparisonFreeList1": "75 वर्ष और उससे अधिक आयु के वरिष्ठ नागरिक",
        "services.comparisonFreeList2": "शारीरिक रूप से विकलांग व्यक्ति (कोई भी आयु)",
        "services.comparisonFreeList3": "नर्सिंग, चिकित्सा, कल्याण और दैनिक सहायता शामिल है",
        "services.comparisonPaidTitle": "समर्थित सेवाएं",
        "services.comparisonPaidList1": "75 वर्ष से कम आयु के वरिष्ठ नागरिक",
        "services.comparisonPaidList2": "विशिष्ट या विस्तारित चिकित्सा देखभाल",
        "services.comparisonPaidList3": "अनुकूलित बुजुर्ग देखभाल योजनाएं",
        "services.comparisonNote": "सभी सेवा संरचनाएं स्पष्ट रूप से, नैतिक रूप से और बिना किसी छिपी हुई शर्तों के बताई गई हैं।",

        // Donation Page (Hindi)
        "donation.heroTitle": "बुजुर्गों की देखभाल के लिए दान करें",
        "donation.heroSubtitle": "गरिमा, आराम और आशा दें",
        "donation.heroDesc": "आपकी दयालुता यह सुनिश्चित करती है कि बूढ़ा होने का मतलब कभी भुला दिया जाना नहीं है।",
        "donation.formTitle": "अभी दान करें और बदलाव लाएं",
        "donation.formIntro": "आपका सहयोग हमारे बुजुर्गों को भोजन, दवा और गरिमा प्रदान करता है।",
        "donation.amountLabel": "राशि चुनें (INR)",
        "donation.minAmount": "न्यूनतम दान: ₹100",
        "donation.personalDetails": "व्यक्तिगत विवरण",
        "donation.fullName": "पूरा नाम",
        "donation.email": "ईमेल पता",
        "donation.phone": "फ़ोन नंबर",
        "donation.btn": "अभी दान करें",
        "donation.secured": "सुरक्षित भुगतान",
        "donation.whyMattersTitle": "आपका दान क्यों मायने रखता है",
        "donation.whyMattersDesc": "कई बुजुर्ग उन चुनौतियों का सामना करते हैं जो दैनिक जीवन को कठिन बनाती हैं।",
        "donation.impact1": "अकेलापन और परित्याग",
        "donation.impact2": "पुरानी स्वास्थ्य स्थितियां",
        "donation.impact3": "सीमित या कोई आय नहीं",
        "donation.impact4": "शारीरिक चुनौतियां",
        "donation.usageTitle": "आपके दान का उपयोग कैसे होता है",
        "donation.usageDesc": "हमारा मानना है कि प्रत्येक दाता स्पष्टता और विश्वास का हकदार है।",
        "donation.medical": "चिकित्सा देखभाल और नर्सिंग",
        "donation.food": "भोजन और आवश्यक वस्तुएं",
        "donation.shelter": "सुरक्षित आश्रय",
        "donation.wellness": "भावनात्मक कल्याण",
        "donation.impactNote": "समय पर समर्थन के बिना, उनके बाद के वर्ष शांति के बजाय संघर्ष बन जाते हैं। जब आप नागपुर में एक बुजुर्ग देखभाल एनजीओ को दान करते हैं, तो आप यह सुनिश्चित करने में मदद करते हैं कि कोई भी बुजुर्ग देखभाल, सुरक्षा या गरिमा के बिना न रहे।",
        "donation.impactQuote": "\"आपकी उदारता केवल स्वास्थ्य ही नहीं—बल्कि आशा और आत्म-सम्मान को भी बहाल करती है।\"",
        "donation.usageIntro": "हमारा मानना है कि हर दाता स्पष्टता और विश्वास का हकदार है। प्रत्येक योगदान वास्तविक, मापने योग्य देखभाल की ओर निर्देशित होता है।",
        "donation.medicalList1": "नियमित डॉक्टर परामर्श",
        "donation.medicalList2": "दवाएं और चल रहा उपचार",
        "donation.medicalList3": "स्वच्छता और गतिशीलता के लिए नर्सिंग सहायता",
        "donation.foodList1": "ताज़ा, संतुलित भोजन",
        "donation.foodList2": "स्वच्छ पीने का पानी",
        "donation.foodList3": "व्यक्तिगत स्वच्छता आइटम",
        "donation.shelterList1": "सुरक्षित आवास",
        "donation.shelterList2": "स्वच्छ, बुजुर्ग-अनुकूल स्थान",
        "donation.shelterList3": "24/7 पर्यवेक्षण और सहायता",
        "donation.wellnessList1": "योग और हल्की फिटनेस",
        "donation.wellnessList2": "भावनात्मक साहचर्य",
        "donation.wellnessList3": "सामाजिक आनंदमय गतिविधियाँ",
        "donation.helpsTitle": "आपका दान किसकी मदद करता है",
        "donation.helps1Title": "वरिष्ठ नागरिक 75+",
        "donation.helps1Sub": "(मुफ्त देखभाल प्रदान की जाती है)",
        "donation.helps2Title": "शारीरिक रूप से विकलांग",
        "donation.helps2Sub": "(सार्वभौमिक समर्थन)",
        "donation.helps3Title": "बिना परिवार वाले बुजुर्ग",
        "donation.helps3Sub": "(दयालु सहायता)",
        "donation.helpsNote": "आपकी उदारता सुनिश्चित करती है कि देखभाल सामर्थ्य के आधार पर नहीं, बल्कि आवश्यकता के आधार पर प्रदान की जाए।",
        "donation.trustTitle": "सुरक्षित ऑनलाइन दान और रसीद आश्वासन",
        "donation.trustIntro": "हम सुरक्षित और पारदर्शी दान विकल्प प्रदान करते हैं:",
        "donation.trustList1": "सुरक्षित और एन्क्रिप्टेड भुगतान गेटवे",
        "donation.trustList2": "तल्काल पावती",
        "donation.trustList3": "दान रसीद प्रदान की गई",
        "donation.trustList4": "पारदर्शी लेखांकन और नैतिक शासन",
        "donation.commitmentTitle": "विश्वास के प्रति हमारी प्रतिबद्धता",
        "donation.commitmentList1": "• धन का नैतिक उपयोग",
        "donation.commitmentList2": "• स्पष्ट दस्तावेज़ीकरण",
        "donation.commitmentList3": "• ईमानदार संचार",
        "donation.commitmentList4": "• दीर्घकालिक प्रभाव पर ध्यान",
        "donation.commitmentNote": "हर रुपये को एक जिम्मेदारी के रूप में माना जाता है।",

        // Contact Page (Hindi)
        "contact.heroTitle": "हमसे संपर्क करें",
        "contact.heroDesc": "हमें आपसे सुनना अच्छा लगेगा। चाहे आपके पास प्रश्न हों या सहायता की आवश्यकता हो।",
        "contact.locationTitle": "हमारा स्थान",
        "contact.phoneTitle": "फ़ोन",
        "contact.emailTitle": "ईमेल",
        "contact.whoTitle": "हमसे किसे संपर्क करना चाहिए?",
        "contact.families": "परिवार और देखभाल करने वाले",
        "contact.familiesDesc": "देखभाल के लिए संपर्क करना एक भावनात्मक निर्णय है। हम आपको धैर्यपूर्वक मार्गदर्शन करेंगे।",
        "contact.donors": "दाता और भागीदार",
        "contact.donorsDesc": "साथ मिलकर, हम स्थायी प्रभाव पैदा कर सकते हैं।",
        "contact.volunteers": "स्वयंसेवक",
        "contact.volunteersDesc": "आपका समय और करुणा जीवन बदल सकती है।",
        "contact.volunteerBtn": "स्वयंसेवक बनें",
        "contact.supportBtn": "बुजुर्गों का समर्थन करें",
        "contact.address": "89, एनआईटी गार्डन के पास, टेलीकॉम नगर, प्रताप नगर, नागपुर, महाराष्ट्र 440022",
        "contact.partnersList1": "बुजुर्गों की देखभाल के लिए दान करें",
        "contact.partnersList2": "दीर्घकालिक या सीएसआर साझेदारी का अन्वेषण करें",
        "contact.partnersList3": "समझें कि आपका योगदान कैसे प्रभाव डालता है",
        "contact.partnersNote": "हम अपने सभी कार्यों में पूर्ण पारदर्शिता और जवाबदेही में विश्वास करते हैं।",

        // Volunteer Page (Hindi Additional)
        "volunteer.whyMatters": "स्वयंसेवा क्यों मायने रखती है",
        "volunteer.whyMattersDesc": "जैसे-जैसे लोग बूढ़े होते हैं, उन्हें दवा की नहीं—बल्कि साथ की कमी खलती है।",
        "volunteer.role1": "बुजुर्गों के साथ समय बिताएं",
        "volunteer.role2": "कल्याण और गतिविधि सहायता",
        "volunteer.role3": "देखभाल और सहायता",
        "volunteer.role4": "प्रशासनिक और आउटरीच",
        "volunteer.role5": "सीएसआर और समूह स्वयंसेवा",
        "volunteer.gainTitle": "एक स्वयंसेवक के रूप में आप क्या प्राप्त करते हैं",
        "volunteer.whoCanTitle": "स्वयंसेवक कौन बन सकता है?",
        "volunteer.rolesTitle": "स्वयंसेवक भूमिकाएं और अवसर",
        "volunteer.readyTitle": "बदलाव लाने के लिए तैयार हैं?",
        "volunteer.readyDesc": "हमारे दयालु स्वयंसेवकों के समुदाय में शामिल हों और हमारे बुजुर्गों के जीवन में खुशी लाएं।",
        "volunteer.registerCTA": "स्वयंसेवक के रूप में पंजीकरण करें",
        "volunteer.joinCTA": "हमारी देखभाल समुदाय में शामिल हों",
        "volunteer.formIntro": "हमारे स्वयंसेवक समुदाय का हिस्सा बनने के लिए अपना विवरण भरें",
        "volunteer.registerTitle": "स्वयंसेवक पंजीकरण",
        "volunteer.formName": "पूरा नाम",
        "volunteer.formEmail": "ईमेल पता",
        "volunteer.formPhone": "फ़ोन नंबर",
        "volunteer.formDOB": "जन्म तिथि",
        "volunteer.formQual": "योग्यता / पदनाम",
        "volunteer.formArea": "रुचि का क्षेत्र",
        "volunteer.formAvail": "उपलब्धता",
        "volunteer.submitBtn": "पंजीकरण जमा करें",
        "volunteer.benefit1": "अकेलापन और भावनात्मक अलगाव को कम करें",
        "volunteer.benefit2": "शारीरिक रूप से चुनौतीपूर्ण व्यक्तियों का समर्थन करें",
        "volunteer.benefit3": "सामुदायिक जिम्मेदारी को मजबूत करें",
        "volunteer.benefit4": "अपनी उपस्थिति से खुशी के पल बनाएं",
        "volunteer.highlightText": "स्वयंसेवा हमारे बुजुर्गों को याद दिलाती है कि उन्हें देखा, मूल्यवान और सम्मानित किया जाता है।",
        "volunteer.whoCard1": "सार्थक सामाजिक कार्य अनुभव की तलाश में छात्र",
        "volunteer.whoCard2": "कामकाजी पेशेवर जो समाज को वापस देना चाहते हैं",
        "volunteer.whoCard3": "सेवानिवृत्त लोग जो अपनी बुद्धि और समय साझा करना चाहते हैं",
        "volunteer.whoCard4": "सीएसआर गतिविधियों में रुचि रखने वाले कॉर्पोरेट समूह",
        "volunteer.whoCard5": "कलाकार, संगीतकार, या कहानीकार जो खुशी ला सकते हैं",
        "volunteer.whoCard6": "सहानुभूति, धैर्य और दयालु हृदय वाला कोई भी",
        "volunteer.gain1": "उद्देश्य और पूर्ति की भावना",
        "volunteer.gain2": "सामाजिक कार्य और देखभाल में वास्तविक अनुभव",
        "volunteer.gain3": "वरिष्ठ नागरिकों और साथी स्वयंसेवकों के साथ सार्थक संबंध",
        "volunteer.gain4": "सहानुभूति और धैर्य के माध्यम से व्यक्तिगत विकास",
        "volunteer.gain5": "स्वयंसेवक प्रमाणपत्र और मान्यता",
        "volunteer.gain6": "किसी के जीवन में ठोस बदलाव लाने का अवसर",
        "volunteer.role1Item1": "बातचीत और साहचर्य में संलग्न हों",
        "volunteer.role1Item2": "उनकी जीवन कहानियों और अनुभवों को सुनें",
        "volunteer.role1Item3": "भोजन साझा करें और विशेष अवसरों का जश्न मनाएं",
        "volunteer.role1Item4": "इनडोर गेम खेलें या उन्हें पढ़कर सुनाएं",
        "volunteer.role2Item1": "कोमल शारीरिक गतिविधियों या योग सत्रों का आयोजन करें",
        "volunteer.role2Item2": "संगीत, कला या शिल्प कार्यशालाओं का नेतृत्व करें",
        "volunteer.role2Item3": "मनोरंजक सैर और समूह गतिविधियों में सहायता करें",
        "volunteer.role2Item4": "बागवानी या हल्की बाहरी गतिविधियों में मदद करें",
        "volunteer.role3Item1": "दैनिक गतिशीलता और आंदोलन समर्थन में मदद करें",
        "volunteer.role3Item2": "भोजन के समय सहायता करें",
        "volunteer.role3Item3": "स्वच्छता और व्यक्तिगत देखभाल दिनचर्या का समर्थन करें (प्रशिक्षण के साथ)",
        "volunteer.role3Item4": "चिकित्सा नियुक्तियों के लिए बुजुर्गों के साथ जाएं",
        "volunteer.role4Item1": "दस्तावेज़ीकरण और रिकॉर्ड-कीपिंग में मदद करें",
        "volunteer.role4Item2": "सोशल मीडिया और जागरूकता अभियानों में सहायता करें",
        "volunteer.role4Item3": "धन उगाही और दान अभियानों का समर्थन करें",
        "volunteer.role4Item4": "स्वयंसेवक कार्यक्रम और कार्यक्रमों का समन्वय करें",
        "volunteer.role5Item1": "बुजुर्गों के साथ टीम-बिल्डिंग गतिविधियों का आयोजन करें",
        "volunteer.role5Item2": "स्वास्थ्य शिविर या जागरूकता सत्र आयोजित करें",
        "volunteer.role5Item3": "विशेष कार्यक्रमों को प्रायोजित करें (जन्मदिन, त्यौहार)",
        "volunteer.role5Item4": "कौशल-आधारित स्वयंसेवा प्रदान करें (कानूनी, चिकित्सा, तकनीकी सहायता)"
    },

    mr: {
        // Navigation (Marathi)
        "nav.home": "मुख्यपृष्ठ",
        "nav.about": "आमच्याबद्दल",
        "nav.services": "सेवा",
        "nav.donation": "देणगी",
        "nav.volunteer": "स्वयंसेवक",
        "nav.contact": "संपर्क",

        // Hero Section (Marathi)
        "hero.title": "नागपूरमधील वृद्ध काळजी एनजीओ — जिथे प्रत्येक वृद्ध सन्मानाने जगतो",
        "hero.subtitle": "हे फक्त वृद्धाश्रम नाही. हे सन्मान, सुरक्षा आणि आपलेपणाचे घर आहे.",
        "hero.highlight": "शांतता आणि प्रेमात हसा.",
        "hero.donateBtn": "आता देणगी द्या",
        "hero.volunteerBtn": "स्वयंसेवक बना",

        // Mission Section (Marathi)
        "mission.heading": "कारण म्हातारे होणे म्हणजे कधीही एकटे असणे नाही",
        "mission.description": "नागपूरमधील आमच्या वृद्ध काळजी एनजीओमध्ये, आम्ही विश्वास ठेवतो की प्रत्येक वृद्ध व्यक्तीला आदर, काळजी आणि शांतता आणि सन्मानाने भरलेले जीवन मिळण्यास पात्र आहे। आम्ही हे सुनिश्चित करण्यासाठी अस्तित्वात आहोत की वृद्ध - विशेषत: जे असुरक्षित, सोडून दिलेले किंवा शारीरिकदृष्ट्या अपंग आहेत - त्यांची करुणा, वैद्यकीय जबाबदारी आणि मानवी उबदारपणाने काळजी घ्यावी.",

        // Who We Are Section (Marathi)
        "home.careDecor": "काळजी",
        "home.whoWeAre": "आम्ही कोण आहोत",
        "home.trustedTitle": "महाराष्ट्रातील एक विश्वसनीय ज्येष्ठ नागरिक सेवा संस्था",
        "home.charitableText": "आम्ही वृद्धांची काळजी आणि शारीरिकदृष्ट्या अपंग व्यक्तींच्या आधारासाठी समर्पित एक धर्मादाय संस्था आहोत.",
        "home.missionIntro": "आमचे ध्येय साधे तरीही शक्तिशाली आहे:",
        "home.missionStatement": "वृद्धांची कुटुंबाप्रमाणे सेवा करणे — सहानुभूती, अखंडता आणि व्यावसायिक काळजीसह.",
        "home.provideServicesTo": "आम्ही खालील लोकांसाठी मोफत आणि समर्थित सेवा प्रदान करतो:",
        "home.serviceList1": "75 वर्षे आणि त्याहून अधिक वयाचे ज्येष्ठ नागरिक",
        "home.serviceList2": "शारीरिकदृष्ट्या अपंग व्यक्ती (वयाची मर्यादा नाही)",
        "home.serviceList3": "ज्या वृद्धांना आर्थिक किंवा कौटुंबिक आधार नाही",
        "home.structuredCare": "संरचित काळजी, वैद्यकीय लक्ष आणि भावनिक सोबतीद्वारे, आम्ही वृद्धांना त्यांची नंतरची वर्षे आरामात आणि आत्मविश्वासाने जगण्यास मदत करतो.",

        // Services Section (Marathi)
        "home.servicesTitle": "नागपूरमधील आमच्या वृद्ध काळजी सेवा",
        "home.servicesSubtitle": "सर्वसमावेशक, दयाळू आणि प्रतिष्ठित काळजी",
        "home.servicesDesc": "आम्ही महाराष्ट्रामध्ये ज्येष्ठ नागरिक काळजी सेवांची विस्तृत श्रेणी ऑफर करतो, जी शारीरिक, भावनिक आणि वैद्यकीय गरजा पूर्ण करण्यासाठी डिझाइन केलेली आहे.",
        "home.serviceCardTitle1": "असिस्टेड लिव्हिंग केअर",
        "home.serviceCardDesc1": "ज्या वृद्धांना दैनंदिन वैद्यकीय देखरेख आणि वैयक्तिक मदतीची आवश्यकता असते त्यांच्यासाठी.",
        "home.serviceCardTitle2": "इंडिपेंडेंट लिव्हिंग",
        "home.serviceCardDesc2": "जे ज्येष्ठ नागरिक वैद्यकीयदृष्ट्या स्थिर आहेत परंतु समुदाय, सुरक्षा आणि आधार शोधत आहेत त्यांच्यासाठी.",
        "home.serviceCardTitle3": "घरगुती आरोग्य सेवा",
        "home.serviceCardDesc3": "जे वृद्ध नागपूरमध्ये घरीच काळजी घेणे पसंत करतात त्यांच्यासाठी व्यावसायिक नर्सिंग आणि केअरगिव्हर सपोर्ट.",
        "home.serviceCardTitle4": "डिमेंशिया आणि मेमरी केअर",
        "home.serviceCardDesc4": "डिमेंशिया असलेल्या ज्येष्ठ नागरिकांसाठी सुरक्षित, संरचित आणि भावनिकदृष्ट्या संवेदनशील काळजी.",
        "home.serviceCardTitle5": "पोस्ट-ऑपरेटिव्ह आणि रिकव्हरी केअर",
        "home.serviceCardDesc5": "शस्त्रक्रिया, दुखापत किंवा हॉस्पिटलायझेशननंतर बरे होणाऱ्या वृद्धांसाठी आधार.",
        "home.serviceCardTitle6": "दीर्घकालीन आजार व्यवस्थापन",
        "home.serviceCardDesc6": " संधिवात, हृदयविकार, दमा, कर्करोग आणि दीर्घकालीन स्थितींसाठी काळजी.",
        "home.exploreServicesBtn": "सर्व सेवा पहा",

        // Trust Section (Marathi)
        "home.trustTitle": "कुटुंबे आमच्यावर का विश्वास ठेवतात",
        "home.trustSubtitle": "नागपूरमधील एक काळजी घेणारे वृद्धाश्रम ज्याचा प्रभाव सिद्ध आहे",
        "home.trustList1": "वृद्धांच्या काळजीसाठी समर्पित 200+ बेड",
        "home.trustList2": "प्रशिक्षित नर्स, केअरगिव्हर्स आणि वैद्यकीय कर्मचारी",
        "home.trustList3": "75+ वयोगटातील ज्येष्ठ नागरिकांसाठी मोफत काळजी",
        "home.trustList4": "शारीरिकदृष्ट्या अपंग व्यक्तींसाठी मोफत आधार",
        "home.trustList5": "24/7 देखरेख आणि वैद्यकीय निगराणी",
        "home.trustList6": "भावनिक कल्याण, सन्मान आणि आदरावर लक्ष",

        // Support Section (Marathi)
        "home.supportTitle": "तुमचे समर्थन जीवन बदलू शकते",
        "home.supportSubtitle": "नागपूरमधील वृद्ध काळजीसाठी देणगी द्या",
        "home.supportDesc": "अनेक वृद्ध आमच्याकडे उत्पन्नाशिवाय, कौटुंबिक आधाराशिवाय आणि गंभीर आरोग्य गरजांसह येतात. तुमचे योगदान आम्हाला हे प्रदान करण्यास मदत करते:",
        "home.supportList1": "मोफत वैद्यकीय उपचार आणि नर्सिंग केअर",
        "home.supportList2": "पौष्टिक जेवण आणि सुरक्षित निवारा",
        "home.supportList3": "औषधे, निदान आणि कल्याण उपक्रम",
        "home.supportList4": "भावनिक आधार आणि सोबत",
        "home.transparencyNote": "पारदर्शक वापर | देणगी पावत्या उपलब्ध | CSR-फ्रेंडली",
        "home.donateNowBtn": "आता देणगी द्या - आजच एका वृद्धाला आधार द्या",

        // CTA Section (Marathi)
        "home.ctaTitle": "एकत्रितपणे, आपण अधिक चांगली काळजी घेऊ शकतो",
        "home.ctaDesc": "जेव्हा समाज आपल्या वृद्धांचा सन्मान आणि संरक्षण करतो तेव्हाच तो खरोखर प्रगतीशील असतो. तुमच्या पाठिंब्याने, आम्ही हे सुनिश्चित करू शकतो की नागपूरमधील कोणताही वृद्ध मागे राहणार नाही.",
        "home.makeDonationBtn": "देणगी द्या",
        "home.contactTeamBtn": "आमच्या टीमशी संपर्क साधा",

        // Volunteer Page (Marathi)
        "volunteer.heroTitle": "आमच्यासोबत स्वयंसेवक व्हा —",
        "volunteer.heroSpan": "एका वृद्धाच्या हसण्याचे कारण बना",
        "volunteer.subtitle": "नागपूरमधील वृद्ध काळजी एनजीओसाठी स्वयंसेवक",
        "volunteer.intro1": "एल्डर जॉय केअर सेंटरमध्ये, स्वयंसेवक आमच्या मिशनचे हृदय आहेत. तुमचा वेळ, कौशल्ये आणि दयाळूपणा थेट त्या वृद्ध व्यक्तींच्या जीवनावर परिणाम करतो ज्यांना काळजी, सहवास आणि सन्मानाची आवश्यकता आहे.",
        "volunteer.intro2": "तुम्ही विद्यार्थी असाल, कामकाजी व्यावसायिक, सेवानिवृत्त, किंवा परत देऊ इच्छिणारे कोणीही असाल - तुम्ही मूर्त फरक करू शकता.",
        "volunteer.alreadyVolunteer": "आधीच स्वयंसेवक आहात?",
        "volunteer.generateId": "तुम्ही आमच्यासोबत तुमचा नोंदणी पूर्ण केल्यास, तुम्ही खाली तुमचे अधिकृत स्वयंसेवक ओळखपत्र तयार करू शकता.",
        "volunteer.generateIdBtn": "आता ओळखपत्र तयार करा",

        // Footer (Marathi)
        "footer.quickLinks": "द्रुत दुवे",
        "footer.contact": "आमच्याशी संपर्क साधा",
        "footer.follow": "आम्हाला फॉलो करा",
        "footer.copyright": "कॉपीराइट © 2026 एल्डर जॉय केअर सेंटर | द्वारे समर्थित",

        // About Page (Marathi)
        "about.introTitle": "ज्येष्ठ नागरिक आणि शारीरिकदृष्ट्या अपंग व्यक्तींच्या सेवेसाठी समर्पित एक सेवाभावी संस्था",
        "about.introText": "आम्ही नागपूरमध्ये वृद्धांची काळजी आणि शारीरिकदृष्ट्या अपंग व्यक्तींच्या आधारासाठी केंद्रित एक धर्मादाय संस्था आहोत.",
        "about.belief": "\"प्रत्येक मानवी जीवनाला सन्मान, काळजी आणि आदर मिळण्याचा हक्क आहे—प्रत्येक टप्प्यावर आणि प्रत्येक क्षमतेमध्ये.\"",
        "about.whoWeServeTitle": "आम्ही कोणाची सेवा करतो",
        "about.seniorCitizens": "ज्येष्ठ नागरिक",
        "about.seniorCitizensDesc": "विशेषतः 75 वर्षे आणि त्याहून अधिक वयाचे ज्यांना समर्पित आधाराची आवश्यकता आहे.",
        "about.physicallyChallenged": "शारीरिकदृष्ट्या अपंग",
        "about.physicallyChallengedDesc": "सर्व वयोगटातील विविध क्षमता असलेल्या व्यक्तींसाठी सार्वत्रिक मदत.",
        "about.vulnerableElders": "असुरक्षित वृद्ध",
        "about.vulnerableEldersDesc": "ज्यांना कौटुंबिक आधार किंवा आर्थिक स्थिरता नाही अशांना आधार देणे.",
        "about.missionTitle": "आमचे ध्येय",
        "about.missionDesc": "\"एल्डर जॉय केअर सेंटर एक असे घर प्रदान करण्यासाठी वचनबद्ध आहे जिथे रहिवाशांना उबदारपणा, काळजी आणि आपलेपणा अनुभवता येईल.\"",
        "about.visionTitle": "आमची दृष्टी (Vision)",
        "about.visionDesc": "एक अशी समाज तयार करणे जिथे प्रत्येक वृद्ध मूल्यवान, समर्थित आणि गौरव आणि आनंदाने जगण्यास सक्षम वाटतो.",
        "about.valuesTitle": "आमची मूल्ये",
        "about.dignityTitle": "सन्मान सर्वोपरि",
        "about.dignityDesc": "आम्ही प्रत्येक व्यक्तीच्या जीवन प्रवासाचा आदर करतो आणि सन्मानाने काळजी घेतली जाईल याची खात्री करतो.",
        "about.compassionTitle": "कृतीतून करुणा",
        "about.compassionDesc": "काळजी ही केवळ वैद्यकीय नाही—ती भावनिक, सामाजिक आणि मानवी आहे.",
        "about.integrityTitle": "अखंडता आणि पारदर्शकता",
        "about.integrityDesc": "आम्ही नैतिक कामकाज आणि संसाधनांच्या जबाबदार वापरासाठी वचनबद्ध आहोत.",
        "about.communityTitle": "सामाजिक जबाबदारी",
        "about.visionDesc": "एक अशी समाज तयार करणे जिथे प्रत्येक वृद्ध मूल्यवान, समर्थित आणि गौरव आणि आनंदाने जगण्यास सक्षम वाटतो.",
        "about.approachTitle": "आमच्या दृष्टिकोनाचे हृदय",
        "about.approachDesc": "आमचा दृष्टिकोन रचनाबद्ध आरोग्य सेवा प्रणाली आणि खोल भावनिक समजूत यांचे संयोजन करतो, ज्यामुळे वृद्ध भीतींत्याच्या जागी आरामात आणि अवलंबनाच्या जागी आत्मविश्वासाने जगू शकतात.",

        // Services Page (Marathi)
        "services.heroTitle": "नागपूरमधील सर्वसमावेशक वृद्ध काळजी सेवा",
        "services.heroDesc": "आमची एनजीओ वैद्यकीय काळजी, दैनंदिन मदत आणि भावनिक कल्याणाद्वारे समग्र समर्थन प्रदान करते.",
        "services.eligibilityTitle": "आमच्या सेवांचा लाभ कोणाला मिळू शकतो",
        "services.eligibilitySubtitle": "पात्रता आणि समर्थन संरचना",
        "services.eligibilityQuote": "\"आमच्या सेवा गरज, असुरक्षितता आणि सन्मानाच्या आधारावर प्रदान केल्या जातात.\"",
        "services.senior75": "ज्येष्ठ नागरिक 75+",
        "services.freeCare": "मोफत वृद्ध काळजी सेवा",
        "services.physicallyChallenged": "शारीरिकदृष्ट्या अपंग",
        "services.freeSupport": "मोफत काळजी आणि समर्थन",
        "services.seniorsBelow75": "75 पेक्षा कमी वयाचे ज्येष्ठ",
        "services.supportedPlans": "समर्थित योजना",
        "services.nursingTitle": "नागपूरमध्ये नर्सिंग केअर",
        "services.nursingDesc": "आम्ही प्रशिक्षित कर्मचाऱ्यांद्वारे चोवीस तास व्यावसायिक नर्सिंग केअर प्रदान करतो.",
        "services.medicalTitle": "वैद्यकीय मदत आणि नियमित तपासणी",
        "services.medicalDesc": "आमचे वैद्यकीय काळजी मॉडेल लवकर निदान आणि सातत्यावर केंद्रित आहे.",
        "services.fitnessTitle": "योग आणि हलका व्यायाम",
        "services.fitnessDesc": "स्वातंत्र्य राखण्यात शारीरिक हालचाल महत्त्वाची भूमिका बजावते.",
        "services.homeVisitTitle": "घरी वृद्धांची काळजी",
        "services.homeVisitDesc": "जे ज्येष्ठ त्यांच्या घरी राहणे पसंत करतात, आम्ही त्यांच्यासाठी व्यावसायिक घरगुती काळजी प्रदान करतो.",
        "services.nursingSubtitle": "नर्सिंग सहाय्यामध्ये हे समाविष्ट आहे:",
        "services.nursingList1": "आंघोळ, जेवण आणि हालचालींसारख्या दैनंदिन क्रियाकलापांमध्ये मदत",
        "services.nursingList2": "औषध प्रशासन आणि देखरेख",
        "services.nursingList3": "हॉस्पिटलायझेशन नंतर नर्सिंग केअर",
        "services.nursingList4": "अथरुणग्रस्त आणि हालचालीत अडचण असलेल्या वृद्धांसाठी आधार",
        "services.nursingList5": "करुणापूर्ण जीवनाच्या अंताची काळजी",
        "services.nursingNote": "सर्व काळजी संयमाने आणि आदराने दिली जाते, दिनचर्येपेक्षा सन्मानाला प्राधान्य दिले जाते.",
        "services.medicalSubtitle": "वैद्यकीय सेवांमध्ये हे समाविष्ट आहे:",
        "services.medicalList1": "नियमित डॉक्टरांचा सल्ला",
        "services.medicalList2": "महत्वाच्या पॅरामीटर्सचे निरीक्षण (बीपी, साखर, O2)",
        "services.medicalList3": "प्रतिबंधात्मक आरोग्य तपासणी",
        "services.medicalList4": "दीर्घकालीन परिस्थितीचे व्यवस्थापन",
        "services.medicalList5": "रुग्णालये आणि तज्ञांशी समन्वय",
        "services.medicalNote": "हे सातत्यपूर्ण वैद्यकीय देखरेख आणि वेळेवर हस्तक्षेप सुनिश्चित करते.",
        "services.fitnessItem1Title": "हालचाल",
        "services.fitnessItem1Desc": "खुर्ची योग आणि मार्गदर्शित स्ट्रेचिंग",
        "services.fitnessItem2Title": "श्वास",
        "services.fitnessItem2Desc": "फुफ्फुसाच्या आरोग्यासाठी व्यायाम",
        "services.fitnessItem3Title": "लवचिकता",
        "services.fitnessItem3Desc": "संतुलन आणि लवचिकता दिनचर्या",
        "services.fitnessItem4Title": "विश्रांती",
        "services.fitnessItem4Desc": "तणाव कमी करणारी सत्रे",
        "services.fitnessNote": "हे कार्यक्रम हालचाल सुधारण्यास, अस्वस्थता कमी करण्यास आणि वृद्ध आणि शारीरिकदृष्ट्या अपंग व्यक्तींमध्ये आत्मविश्वास वाढवण्यास मदत करतात.",
        "services.homeVisitSubtitle": "घरगुती आधारात हे समाविष्ट आहे:",
        "services.homeVisitList1": "नर्सिंग आणि केअरगिव्हर भेटी",
        "services.homeVisitList2": "घरीच होणाऱ्या आरोग्य तपासण्या",
        "services.homeVisitList3": "औषधांची आठवण आणि मदत",
        "services.homeVisitList4": "भावनिक आधार आणि नियमित देखरेख",
        "services.homeVisitList5": "कुटुंब सदस्य आणि काळजीवाहकांसाठी मार्गदर्शन",
        "services.homeVisitNote": "ही सेवा वृद्धांना परिचित वातावरणात सुरक्षित आणि समर्थित राहण्याची परवानगी देते.",
        "services.comparisonTitle": "मोफत वि समर्थित वृद्ध काळजी सेवा",
        "services.comparisonSubtitle": "पारदर्शक आणि नैतिक संरचना",
        "services.comparisonFreeTitle": "मोफत काळजी सेवा",
        "services.comparisonFreeList1": "75 वर्षे आणि त्याहून अधिक वयाचे ज्येष्ठ नागरिक",
        "services.comparisonFreeList2": "शारीरिकदृष्ट्या अपंग व्यक्ती (कोणत्याही वयाचे)",
        "services.comparisonFreeList3": "नर्सिंग, वैद्यकीय, कल्याण आणि दैनंदिन मदत समाविष्ट आहे",
        "services.comparisonPaidTitle": "समर्थित सेवा",
        "services.comparisonPaidList1": "75 वर्षांखालील ज्येष्ठ नागरिक",
        "services.comparisonPaidList2": "विशेष किंवा विस्तारित वैद्यकीय काळजी",
        "services.comparisonPaidList3": "सानुकूलित वृद्ध काळजी योजना",
        "services.comparisonNote": "सर्व सेवा रचना स्पष्टपणे, नैतिकतेने आणि कोणत्याही लपविलेल्या अटींशिवाय सांगितल्या जातात.",

        // Donation Page (Marathi)
        "donation.heroTitle": "वृद्धांच्या काळजीसाठी देणगी द्या",
        "donation.heroSubtitle": "सन्मान, आराम आणि आशा द्या",
        "donation.heroDesc": "तुमची दयाळूपणा हे सुनिश्चित करते की म्हातारे होणे म्हणजे विसरले जाणे नाही.",
        "donation.formTitle": "आता देणगी द्या आणि बदल घडवा",
        "donation.formIntro": "तुमचे समर्थन आमच्या वृद्धांना अन्न, औषध आणि सन्मान प्रदान करते.",
        "donation.amountLabel": "रक्कम निवडा (INR)",
        "donation.minAmount": "किमान देणगी: ₹100",
        "donation.personalDetails": "वैयक्तिक तपशील",
        "donation.fullName": "पूर्ण नाव",
        "donation.email": "ईमेल पत्ता",
        "donation.phone": "फोन नंबर",
        "donation.btn": "आता देणगी द्या",
        "donation.secured": "सुरक्षित पेमेंट",
        "donation.whyMattersTitle": "तुमची देणगी का महत्त्वाची आहे",
        "donation.whyMattersDesc": "अनेक वृद्धांना अशा आव्हानांचा सामना करावा लागतो ज्यामुळे दैनंदिन जीवन कठीण होते.",
        "donation.impact1": "एकाकीपणा आणि त्याग",
        "donation.impact2": "दीर्घकालीन आरोग्य स्थिती",
        "donation.impact3": "मर्यादित किंवा कोणतेही उत्पन्न नाही",
        "donation.impact4": "शारीरिक आव्हाने",
        "donation.usageTitle": "तुमच्या देणगीचा वापर कसा होतो",
        "donation.usageDesc": "आम्ही मानतो की प्रत्येक देणगीदार स्पष्टता आणि विश्वासास पात्र आहे.",
        "donation.medical": "वैद्यकीय काळजी आणि नर्सिंग",
        "donation.food": "अन्न आणि जीवनावश्यक वस्तू",
        "donation.shelter": "सुरक्षित निवारा",
        "donation.wellness": "भावनिक कल्याण",
        "donation.impactNote": "वेळेवर आधाराशिवाय, त्यांची नंतरची वर्षे शांततेऐवजी संघर्ष बनतात. जेव्हा तुम्ही नागपूरमधील वृद्ध काळजी एनजीओला देणगी देता, तेव्हा तुम्ही हे सुनिश्चित करण्यास मदत करता की कोणताही वृद्ध काळजी, सुरक्षा किंवा सन्मानाशिवाय राहणार नाही.",
        "donation.impactQuote": "\"तुमची उदारता केवळ आरोग्यच नाही—तर आशा आणि स्वाभिमान देखील पुनर्संचयित करते.\"",
        "donation.usageIntro": "आम्ही मानतो की प्रत्येक देणगीदार स्पष्टता आणि विश्वासास पात्र आहे. प्रत्येक योगदान वास्तविक, मोजण्यायोग्य काळजीकडे निर्देशित केले जाते.",
        "donation.medicalList1": "नियमित डॉक्टरांचा सल्ला",
        "donation.medicalList2": "औषधे आणि चालू उपचार",
        "donation.medicalList3": "स्वच्छता आणि हालचालींसाठी नर्सिंग मदत",
        "donation.foodList1": "ताजे, संतुलित जेवण",
        "donation.foodList2": "स्वच्छ पिण्याचे पाणी",
        "donation.foodList3": "वैयक्तिक स्वच्छता वस्तू",
        "donation.shelterList1": "सुरक्षित निवास",
        "donation.shelterList2": "स्वच्छ, वृद्धांसाठी अनुकूल जागा",
        "donation.shelterList3": "24/7 देखरेख आणि मदत",
        "donation.wellnessList1": "योग आणि हलका व्यायाम",
        "donation.wellnessList2": "भावनिक सहवास",
        "donation.wellnessList3": "सामाजिक आनंददायी उपक्रम",
        "donation.helpsTitle": "तुमची देणगी कोणाला मदत करते",
        "donation.helps1Title": "ज्येष्ठ नागरिक 75+",
        "donation.helps1Sub": "(मोफत काळजी प्रदान केली)",
        "donation.helps2Title": "शारीरिकदृष्ट्या अपंग",
        "donation.helps2Sub": "(सार्वत्रिक आधार)",
        "donation.helps3Title": "कुटुंब नसलेले वृद्ध",
        "donation.helps3Sub": "(दयाळू मदत)",
        "donation.helpsNote": "तुमची उदारता सुनिश्चित करते की काळजी परवडण्यावर नाही, तर गरजेवर आधारित प्रदान केली जाते.",
        "donation.trustTitle": "सुरक्षित ऑनलाइन देणगी आणि पावती आश्वासन",
        "donation.trustIntro": "आम्ही सुरक्षित आणि पारदर्शक देणगी पर्याय ऑफर करतो:",
        "donation.trustList1": "सुरक्षित आणि एनक्रिप्टेड पेमेंट गेटवे",
        "donation.trustList2": "तात्काळ पावती",
        "donation.trustList3": "देणगी पावती प्रदान केली",
        "donation.trustList4": "पारदर्शक लेखा आणि नैतिक शासन",
        "donation.commitmentTitle": "विश्वासासाठी आमची वचनबद्धता",
        "donation.commitmentList1": "• निधीचा नैतिक वापर",
        "donation.commitmentList2": "• स्पष्ट कागदपत्रे",
        "donation.commitmentList3": "• प्रामाणिक संवाद",
        "donation.commitmentList4": "• दीर्घकालीन प्रभावावर लक्ष",
        "donation.commitmentNote": "प्रत्येक रुपया जबाबदारी म्हणून मानला जातो.",

        // Contact Page (Marathi)
        "contact.heroTitle": "आमच्याशी संपर्क साधा",
        "contact.heroDesc": "आम्हाला तुमच्याकडून ऐकायला आवडेल. तुम्हाला प्रश्न असतील किंवा मदतीची आवश्यकता असेल.",
        "contact.locationTitle": "आमचे स्थान",
        "contact.phoneTitle": "फोन",
        "contact.emailTitle": "ईमेल",
        "contact.whoTitle": "आम्हाला कोणी संपर्क करावा?",
        "contact.families": "कुटुंबे आणि काळजीवाहक",
        "contact.familiesDesc": "काळजीसाठी संपर्क करणे हा एक भावनिक निर्णय आहे. आम्ही तुम्हाला संयमाने मार्गदर्शन करू.",
        "contact.donors": "देणगीदार आणि भागीदार",
        "contact.donorsDesc": "एकत्रितपणे, आपण कायमस्वरूपी प्रभाव निर्माण करू शकतो.",
        "contact.volunteers": "स्वयंसेवक",
        "contact.volunteersDesc": "तुमचा वेळ आणि करुणा जीवन बदलू शकते.",
        "contact.volunteerBtn": "स्वयंसेवक बना",
        "contact.supportBtn": "वृद्धांना समर्थन द्या",
        "contact.address": "89, एनआयटी गार्डन जवळ, टेलिकॉम नगर, प्रताप नगर, नागपूर, महाराष्ट्र 440022",
        "contact.partnersList1": "वृद्धांच्या काळजीसाठी देणगी द्या",
        "contact.partnersList2": "दीर्घकालीन किंवा सीएसआर भागीदारी एक्सप्लोर करा",
        "contact.partnersList3": "तुमचे योगदान कसा प्रभाव पाडते ते समजून घ्या",
        "contact.partnersNote": "आमचा आमच्या सर्व ऑपरेशन्समध्ये पूर्ण पारदर्शकता आणि उत्तरदायित्वावर विश्वास आहे.",

        // Volunteer Page (Marathi Additional)
        "volunteer.whyMatters": "स्वयंसेवा का महत्त्वाची आहे",
        "volunteer.whyMattersDesc": "जसे लोक म्हातारे होतात, त्यांना औषधाची नाही—तर सहवासाची कमतरता जाणवते.",
        "volunteer.role1": "वृद्धांसोबत वेळ घालवा",
        "volunteer.role2": "कल्याण आणि क्रियाकलाप आधार",
        "volunteer.role3": "काळजी आणि समर्थन",
        "volunteer.role4": "प्रशासकीय आणि आउटरीच",
        "volunteer.role5": "सीएसआर आणि समूह स्वयंसेवा",
        "volunteer.gainTitle": "स्वयंसेवक म्हणून तुम्हाला काय मिळते",
        "volunteer.whoCanTitle": "स्वयंसेवक कोण होऊ शकतो?",
        "volunteer.rolesTitle": "स्वयंसेवक भूमिका आणि संधी",
        "volunteer.readyTitle": "बदल घडवण्यासाठी तयार आहात?",
        "volunteer.readyDesc": "आमच्या दयाळू स्वयंसेवकांच्या समुदायात सामील व्हा आणि आमच्या वृद्धांच्या जीवनात आनंद आणा.",
        "volunteer.registerCTA": "स्वयंसेवक म्हणून नोंदणी करा",
        "volunteer.joinCTA": "आमच्या काळजी समुदायात सामील व्हा",
        "volunteer.formIntro": "आमच्या स्वयंसेवक समुदायाचा भाग होण्यासाठी तुमचे तपशील भरा",
        "volunteer.registerTitle": "स्वयंसेवक नोंदणी",
        "volunteer.formName": "पूर्ण नाव",
        "volunteer.formEmail": "ईमेल पत्ता",
        "volunteer.formPhone": "फोन नंबर",
        "volunteer.formDOB": "जन्मतारीख",
        "volunteer.formQual": "पात्रता / पद",
        "volunteer.formArea": "आवडीचे क्षेत्र",
        "volunteer.formAvail": "उपलब्धता",
        "volunteer.submitBtn": "नोंदणी सबमिट करा",
        "volunteer.benefit1": "एकटेपणा आणि भावनिक अलगाव कमी करा",
        "volunteer.benefit2": "शारीरिकदृष्ट्या आव्हानात्मक व्यक्तींना समर्थन द्या",
        "volunteer.benefit3": "समुदाय जबाबदारी मजबूत करा",
        "volunteer.benefit4": "आपल्या उपस्थितीने आनंदाचे क्षण तयार करा",
        "volunteer.highlightText": "स्वयंसेवा आमच्या वृद्धांना आठवण करून देते की त्यांची दखल घेतली जाते, मूल्यवान आणि सन्मानित केले जाते.",
        "volunteer.whoCard1": "सार्थक सामाजिक कार्याचा अनुभव शोधणारे विद्यार्थी",
        "volunteer.whoCard2": "काम करणारे व्यावसायिक जे समाजाला परत द्यायचे आहेत",
        "volunteer.whoCard3": "निवृत्त लोक जे आपले ज्ञान आणि वेळ सामायिक करू इच्छितात",
        "volunteer.whoCard4": "सीएसआर उपक्रमांमध्ये स्वारस्य असलेले कॉर्पोरेट गट",
        "volunteer.whoCard5": "कलाकार, संगीतकार, किंवा कथाकार जे आनंद आणू शकतात",
        "volunteer.whoCard6": "सहानुभूती, धैर्य आणि दयाळू हृदय असलेला कोणीही",
        "volunteer.gain1": "उद्देश आणि पूर्ततेची भावना",
        "volunteer.gain2": "सामाजिक कार्य आणि काळजीमध्ये वास्तविक अनुभव",
        "volunteer.gain3": "वृद्धां आणि सहकारी स्वयंसेवकांशी अर्थपूर्ण संबंध",
        "volunteer.gain4": "सहानुभूती आणि धैर्याद्वारे वैयक्तिक विकास",
        "volunteer.gain5": "स्वयंसेवक प्रमाणपत्र आणि मान्यता",
        "volunteer.gain6": "कोणाच्या तरी जीवनात ठोस फरक घडवण्याची संधी",
        "volunteer.role1Item1": "संभाषण आणि सहवासात गुंतणे",
        "volunteer.role1Item2": "त्यांच्या जीवनाच्या कथा आणि अनुभव ऐका",
        "volunteer.role1Item3": "जेवण सामायिक करा आणि विशेष प्रसंग साजरे करा",
        "volunteer.role1Item4": "घरातील खेळ खेळा किंवा त्यांना वाचून दाखवा",
        "volunteer.role2Item1": "सौम्य शारीरिक क्रियाकलाप किंवा योग सत्रे आयोजित करा",
        "volunteer.role2Item2": "संगीत, कला किंवा हस्तकला कार्यशाळांचे नेतृत्व करा",
        "volunteer.role2Item3": "मनोरंजक सहली आणि गट क्रियाकलापांमध्ये मदत करा",
        "volunteer.role2Item4": "बागकाम किंवा हलक्या बाहेरील क्रियाकलापांमध्ये मदत करा",
        "volunteer.role3Item1": "दैनंदिन हालचाल आणि चळवळ समर्थनात मदत करा",
        "volunteer.role3Item2": "जेवणाच्या वेळी मदत करा",
        "volunteer.role3Item3": "स्वच्छता आणि वैयक्तिक काळजी दिनचर्यांना समर्थन द्या (प्रशिक्षणासह)",
        "volunteer.role3Item4": "वैद्यकीय भेटींसाठी वृद्धांसोबत जा",
        "volunteer.role4Item1": "दस्तऐवजीकरण आणि रेकॉर्ड-कीपिंगमध्ये मदत करा",
        "volunteer.role4Item2": "सोशल मीडिया आणि जागरूकता मोहिमांमध्ये मदत करा",
        "volunteer.role4Item3": "निधी उभारणी आणि देणगी मोहिमांना समर्थन द्या",
        "volunteer.role4Item4": "स्वयंसेवक वेळापत्रक आणि कार्यक्रमांचे समन्वय करा",
        "volunteer.role5Item1": "वृद्धांसह टीम-बिल्डिंग क्रियाकलाप आयोजित करा",
        "volunteer.role5Item2": "आरोग्य शिबिरे किंवा जागरूकता सत्रे आयोजित करा",
        "volunteer.role5Item3": "विशेष कार्यक्रम प्रायोजित करा (वाढदिवस, सण)",
        "volunteer.role5Item4": "कौशल्य-आधारित स्वयंसेवा प्रदान करा (कायदेशीर, वैद्यकीय, तंत्रज्ञान समर्थन)"
    },
};

/**
 * Changes the website language
 * @param {string} lang - Language code (en, hi, mr)
 */
function setLanguage(lang) {
    // Validate language
    if (!translations[lang]) {
        console.warn(`Language '${lang}' not supported. Defaulting to 'en'.`);
        lang = 'en';
    }

    // Get all elements with data-key attribute
    const elements = document.querySelectorAll('[data-key]');

    // Update text content for each element
    elements.forEach(element => {
        const key = element.getAttribute('data-key');
        if (translations[lang][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        } else {
            console.warn(`Translation key '${key}' not found for language '${lang}'`);
        }
    });

    // Update HTML lang attribute
    document.documentElement.setAttribute('lang', lang);

    // Save selected language to localStorage
    localStorage.setItem('selectedLanguage', lang);

    // Update language selector if it exists
    const languageSelect = document.getElementById('languageSelect');
    if (languageSelect && languageSelect.value !== lang) {
        languageSelect.value = lang;
    }
}

/**
 * Initialize language on page load
 */
function initLanguage() {
    // Get saved language from localStorage or default to English
    const savedLanguage = localStorage.getItem('selectedLanguage') || 'en';

    // Apply the language
    setLanguage(savedLanguage);

    // Set up language selector event listener
    const languageSelect = document.getElementById('languageSelect');
    if (languageSelect) {
        languageSelect.value = savedLanguage;
        languageSelect.addEventListener('change', (e) => {
            setLanguage(e.target.value);
        });
    }
}

// Auto-load language when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initLanguage);
} else {
    // DOM is already loaded
    initLanguage();
}
